language: android
jdk: oraclejdk8

# Use the Travis Container-Based Infrastructure
sudo: required

android:
  components:

    #- tools
    - build-tools-23.0.2
    - addon-google_apis-google-23
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23


before_script:
  # Create and start emulator
  - echo yes | android update sdk --all --filter sys-img-armeabi-v7a-android-23 --no-ui --force > /dev/null
  - wget http://dl.google.com/android/android-sdk_r23-linux.tgz
  - tar xzf android-sdk_r23-linux.tgz

  - chmod +x gradlew
  - android list targets
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck
  - ./gradlew assembleRelease


after_success:
  - export BUILD_RESULT="success"

after_failure:
  - export BUILD_RESULT="ERRORED"