language: android

jdk: oraclejdk7

sudo: false

android:
		components:
				- tools
				- platform-tools
				- build-tools-23.0.2
				- android-23
				- extra-android-m2repository
				- sys-img-armeabi-v7a-android-23

before_script: 
		- echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
		- emulator -avd test -no-skin -no-audio -no-window &
		- android-wait-for-emulator

script:

		- android list target
		- chmod +x gradlew
		- ./gradlew connectedAndroidTest --stacktrace