language: android
jdk: oraclejdk7

# Use the Travis Container-Based Infrastructure
sudo: false

android:
  components:
    - build-tools-23.0.2
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-support
    - extra-android-m2repository

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - chmod +x ./gradlew
  - ./gradlew build connectedCheck
  - ./gradlew assembleRelease


after_success:
  - export BUILD_RESULT="success"

after_failure:
  - export BUILD_RESULT="ERRORED"