language: android
jdk: oraclejdk8

# Use the Travis Container-Based Infrastructure
sudo: false

android:
  components:

    - tools
    - build-tools-23.0.2
    - addon-google_apis-google-23
    - android-23
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-addon-google_apis-google-23

before_script:
  # Create and start emulator
  - chmod +x gradlew
  - android list targets
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:23" --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck
  - ./gradlew assembleRelease


after_success:
  - export BUILD_RESULT="success"

after_failure:
  - export BUILD_RESULT="ERRORED"