language: android

jdk: oraclejdk7

sudo: false

env:
    global:
    
        - ANDROID_API_LEVEL=23
        - ANDROID_BUILD_TOOLS_VERSION=23.0.2
        - ANDROID_ABI=google_apis/armeabi-v7a
        - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
        
cache:
    directories:
    
        #- ${TRAVIS_BUILD_DIR}/gradle/caches/
        #- ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/


android:
    components:
    
        - platform-tools
        - tools
        
        - build-tools-23.0.2
        
        - android-23
        - addon-google_apis-google-23
        
        - extra-google-google_play_services
        - extra-android-support
        - extra-google-m2repository
        - extra-android-m2repository

        - sys-img-armeabi-v7a-addon-google_apis-google-23

before_script: 

    - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:23" --abi google_apis/armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator

script:

    - android list target
    - chmod +x gradlew
    - ./gradlew connectedCheck -PdisablePreDex
    - ./gradlew connectedAndroidTest --debug -PdisablePreDex