language: android

android:
    components:
        # Uncomment the lines below if you want to
        # use the latest revision of Android SDK Tools
        - platform-tools
        - tools

        # The BuildTools version used by your project
        - build-tools-23.0.1

        # The SDK version used to compile your project
        - android-23


        # Additional components
        #- extra-google-google_play_services
        #- extra-google-m2repository
        #- extra-android-m2repository
        #- addon-google_apis-google-19
        - sys-img-armeabi-v7a-android-21
        
script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - chmod +x gradlew
    - ./gradlew connectedAndroidTest --stacktrace