language: android

jdk: oraclejdk7

sudo: false

env:
    global:
        - ANDROID_API_LEVEL=21

android:
    components:
        - tools
        - platform-tools
        - build-tools-23.0.0
        - android-23
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-23

before_script: 
    - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:"$ANDROID_API_LEVEL --abi google_apis/armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator

script:

    - android list target
    - chmod +x gradlew
    - ./gradlew connectedCheck -x library:signArchives -PdisablePreDex
    - ./gradlew connectedAndroidTest --info -PdisablePreDex